version: '2.4'
services:
  docker-run:
    image: "glot/docker-run:latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8088:8088"
    env_file:
      - .env
    # environment: # set in EBS ENV
    #   API_ACCESS_TOKEN: replace-with-deploy
