version: '2.4'
services:
  docker-run:
    image: "glot/docker-run:latest"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "8088:8088"
    env_file:
      - .env
    # environment: # set in EBS ENV
    #   API_ACCESS_TOKEN: replace-with-deploy
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    # environment: # set in EBS ENV
    #   RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    #   RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    #   RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - /var/lib/rabbitmq/:/var/lib/rabbitmq/
      - /var/log/rabbitmq/:/var/log/rabbitmq/
